name: Hello World
on: workflow_dispatch
jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: Demo build1
        run: echo "Build 1"
  build2:
    runs-on: ubuntu-latest
    steps:
      - name: Demo build2
        run: echo "Build 2"
  build3:
    runs-on: ubuntu-latest
    steps:
      - name: Demo build3
        run: echo "Build 3"
